---
title: "Dartmoor code through"
output: html_notebook
---

Code through with an extract of data centred around dartmoor, based on the gstat Meuse example.  

###Packages
```{r}
library(tidyverse)
library(sf)
library(sp)
library(gstat)
```

###Data

```{r}
data.shp <- sf::st_read("../data/peat_depths_dartmoor/peat_depths_dartmoor.shp")
summary(data.shp)
data <- data.frame(data.shp)
coords <- st_coordinates(data.shp)
proj4 <- "+proj=tmerc +lat_0=49 +lon_0=-2 +k=0.9996012717 +x_0=400000 +y_0=-100000 +datum=OSGB36 +units=m +no_defs"

data.sp <- sp::SpatialPointsDataFrame(data = data, coords = coords, proj4string = CRS(proj4))

plot(data.sp)
```

```{r}
class(data.sp)
```


### Peat depths

```{r}
summary(data.sp$PEAT_DEPTH)
hist(data.sp$PEAT_DEPTH)
```


### Variograms
```{r}
logPD.vgm = variogram(log(PEAT_DEPTH)~1, data.sp)
logPD.vgm
logPD.fit = fit.variogram(logPD.vgm, model = vgm(1, "Sph", 900, 1))
logPD.fit
plot(logPD.vgm, logPD.fit)
```

NOT LOOKING GOOD, TRY WITHOUT LOG

```{r}
PD.vgm = variogram(PEAT_DEPTH ~1, data.sp)
PD.vgm
plot(PD.vgm)
PD.fit.sph = fit.variogram(PD.vgm, model = vgm(500, "Sph", 2500, 1))
PD.fit.mat = fit.variogram(PD.vgm, model = vgm(500, "Mat", 2500, 1))
PD.fit
plot(PD.vgm, PD.fit.sph)
```










Instead of the constant mean, denoted by \verb|~1|, we can specify a
mean function, e.g. using \verb|~sqrt(dist)| as a predictor variable:

```{r}
logPDr.vgm = variogram(PEAT_DEPTH ~ SLOPE + ELEVATION + consdryday, data.sp)
logPDr.fit = fit.variogram(logPDr.vgm, model = vgm(500, "Mat", 2500, 1))
logPDr.fit
plot(logPDr.vgm, logPDr.fit)
```












