---
title: "predictor explore"
output: html_notebook
---

###Packages
```{r}
library(raster)
library(rgdal)
```


##Crop and save predictor layers

### Import site boundary
```{r}
site_bound <- readOGR(dsn = "../data/dartmoor_national_park.shp", verbose = TRUE)
plot(site_bound)
```

```{r}

boundbox <- site_bound@bbox
```


### Import predictors
```{r}

 # Import environmental and topographic data
 elev <- raster("C:/Christoph/enPeatDepthModel/data/topo_env_data.tif", band = 1)
 # surf <- raster("C:/Christoph/enPeatDepthModel/data/topo_env_data.tif", band = 2)
 # inflow <- raster("C:/Christoph/enPeatDepthModel/data/topo_env_data.tif", band = 3)
 # outflow <- raster("C:/Christoph/enPeatDepthModel/data/topo_env_data.tif", band = 4)
 slope <- raster("C:/Christoph/enPeatDepthModel/data/topo_env_data.tif", band = 5)
 aspect <- raster("C:/Christoph/enPeatDepthModel/data/topo_env_data.tif", band = 6)
 # moorline <- raster("C:/Christoph/enPeatDepthModel/data/topo_env_data.tif", band = 7)

 # Import UKCP09 climate data
 gdd_1960_90_ann <- raster("C:/Christoph/enPeatDepthModel/data/ukcp09GriddedDataAnnPrepd.tif", band = 1)
 gsl_1960_90_ann <- raster("C:/Christoph/enPeatDepthModel/data/ukcp09GriddedDataAnnPrepd.tif", band = 2)
 rain_1960_90_annual <- raster("C:/Christoph/enPeatDepthModel/data/ukcp09GriddedDataAnnPrepd.tif", band = 3)
 rain_daily_mean_1960_90_annual <- raster("C:/Christoph/enPeatDepthModel/data/ukcp09GriddedDataAnnPrepd.tif", band = 4)
 raindays_1mm_1960_90_annual <- raster("C:/Christoph/enPeatDepthModel/data/ukcp09GriddedDataAnnPrepd.tif", band = 5)
 raindays_10mm_1960_90_annual <- raster("C:/Christoph/enPeatDepthModel/data/ukcp09GriddedDataAnnPrepd.tif", band = 6)
 temp_mean_1960_90_annual <- raster("C:/Christoph/enPeatDepthModel/data/ukcp09GriddedDataAnnPrepd.tif", band = 7)
 temp_min_1960_90_annual <- raster("C:/Christoph/enPeatDepthModel/data/ukcp09GriddedDataAnnPrepd.tif", band = 8)
 temp_max_1960_90_annual <- raster("C:/Christoph/enPeatDepthModel/data/ukcp09GriddedDataAnnPrepd.tif", band = 9)
```

make a raster stack
```{r}
 predictors <- stack(
   elev, aspect, slope, 
   gdd_1960_90_ann, gsl_1960_90_ann,
   rain_1960_90_annual, rain_daily_mean_1960_90_annual,
   raindays_10mm_1960_90_annual, raindays_1mm_1960_90_annual,
   temp_mean_1960_90_annual, temp_min_1960_90_annual, 
   temp_max_1960_90_annual
 )
 
 names(predictors) <- c("elev", "aspect", "slope", 
                        "gdd", "gsl", "rain_ann", "rain_daily", "raindays_10mm", 
                        "raindays_1mm", "temp_mean", "temp_min", "temp_max")
 
 #clean up
  rm(
   elev, aspect, slope, 
   gdd_1960_90_ann, gsl_1960_90_ann,
   rain_1960_90_annual, rain_daily_mean_1960_90_annual,
   raindays_10mm_1960_90_annual, raindays_1mm_1960_90_annual,
   temp_mean_1960_90_annual, temp_min_1960_90_annual, 
   temp_max_1960_90_annual
 )
```

crop to training data extent
```{r}
predictors <- crop(x = predictors, y = boundbox)
```

```{r}
plot(predictors)
```

export
```{r}
writeRaster(x = predictors, filename = "../data/predictor_stack.tif", overwrite = TRUE)
```

import cropped raster stack

```{r}
# elev <- raster("../data/predictor_stack.tif", band = 1)
# aspect <- raster("../data/predictor_stack.tif", band = 2)
# slope <- raster("../data/predictor_stack.tif", band = 3)
# outflow <- raster("../data/predictor_stack.tif", band = 4)
# inflow <- raster("../data/predictor_stack.tif", band = 5)
# gdd <- raster("../data/predictor_stack.tif", band = 6)
# gsl <- raster("../data/predictor_stack.tif", band = 7)
# rain_ann <- raster("../data/predictor_stack.tif", band = 8)
# rain_daily <- raster("../data/predictor_stack.tif", band = 9)
# raindays_10mm <- raster("../data/predictor_stack.tif", band = 10)
# raindays_1mm <- raster("../data/predictor_stack.tif", band = 11)
# temp_mean <- raster("../data/predictor_stack.tif", band = 12)
# temp_min <- raster("../data/predictor_stack.tif", band = 13)
# temp_max <- raster("../data/predictor_stack.tif", band = 14)
```

